version: "3"
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - "3306:3306"
    volumes:
      - ../docker/db/data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      MYSQL_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "test"
      PMA_HOST: "database"

  minio:
    image: minio/minio
    volumes:
      - ..docker/minio/data:/data
      - ..docker/minio/config:/root/.minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin1234
    networks:
      - elastic
    command: server /data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:1358,http://127.0.0.1:1358,https://opensource.appbase.io
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - ../docker/esdata:/usr/share/elasticsearch/data+
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      interval: 30s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  dejavu:
    image: appbaseio/dejavu:3.4.7
    container_name: dejavu
    ports:
      - "1358:1358"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  # fastapi:
  #   build: app/
  #   ports:
  #     - 5000:80
  #   networks:
  #     - elastic
  #   container_name: fastapi
  #   depends_on:
  #     - database

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
